# These are supported funding model platforms

github: ermradulsharma
patreon: mradulsharma
open_collective: mradulsharma
ko_fi: mradulsharma
liberapay: mradulsharma
issuehunt: mradulsharma
custom: ['https://www.paypal.com/paypalme/mradulsharma', 'https://www.buymeacoffee.com/mradulsharma']
